repo: https://github.com/evanxg852000/go-eserveless-example
rutime: golang
functions:
- name: API
  type: http
- name: Ticker
  type: cron
  schedule: "*/1 * * * *"
  meta:
    path: "/usr/bin"
    name: dev 
